-- Elsewhere — initial schema
--
-- Organised by the three layers described in docs/spec.md. The layer a table
-- belongs to determines what may be stored in it; see CLAUDE.md.

create extension if not exists postgis;
create extension if not exists pgcrypto;

-- ===========================================================================
-- LAYER 1 — CATALOG
-- Open data (Overture / Foursquare). Ours permanently. All filtering happens
-- here, with no Google calls and no result-count cap.
-- ===========================================================================

-- Normalised cuisine taxonomy. This is OUR taxonomy, not a source's — source
-- categories are mapped onto it at ingest. See category_cuisine_map.
create table cuisines (
  id          serial primary key,
  slug        text not null unique,
  label       text not null,
  parent_id   int references cuisines(id) on delete set null
);

create table places (
  id                uuid primary key default gen_random_uuid(),

  -- Provenance. source_id is the upstream open-data identifier.
  source            text not null check (source in ('overture', 'fsq')),
  source_id         text not null,

  -- Descriptive fields. These come from OPEN DATA, which is why storing them
  -- is permitted. The identical fields from Google may NOT be stored.
  name              text not null,
  location          geography(point, 4326) not null,
  address_line      text,
  locality          text,
  region            text,
  postcode          text,
  country           text,
  website           text,

  source_categories text[] not null default '{}',

  -- Google linkage. place_id is the ONE Google field we may retain
  -- indefinitely, and it is what makes lazy hydration cheap: resolution is
  -- paid once per place across the entire user base, never per user.
  google_place_id             text unique,
  google_place_id_resolved_at timestamptz,
  google_resolution_failed    boolean not null default false,

  -- Set from Google's businessStatus at hydration time. This is a derived
  -- boolean, not retained Google content — it suppresses dead catalog rows.
  permanently_closed boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (source, source_id)
);

-- NOTE: there are deliberately NO columns here for rating, user_rating_count,
-- price_level, opening hours, or review text. Those are Google content and
-- must remain request-scoped. Adding such a column is a schema error and will
-- fail scripts/check-no-google-persistence.sh.

create index places_location_idx on places using gist (location);
create index places_google_place_id_idx on places (google_place_id)
  where google_place_id is not null;
create index places_open_idx on places (permanently_closed)
  where permanently_closed = false;

create table place_cuisines (
  place_id   uuid not null references places(id) on delete cascade,
  cuisine_id int  not null references cuisines(id) on delete cascade,
  primary key (place_id, cuisine_id)
);

create index place_cuisines_cuisine_idx on place_cuisines (cuisine_id);

-- Source category -> our cuisine taxonomy. Generated by an offline Claude pass
-- and then human-reviewed; applied at ingest, never at request time. This
-- mapping is the hardest data problem in the project (spec §11).
create table category_cuisine_map (
  source_category text primary key,
  cuisine_id      int references cuisines(id) on delete set null,
  confidence      real,
  reviewed        boolean not null default false,
  reviewed_at     timestamptz
);

-- ===========================================================================
-- LAYER 3 — PREFERENCE & HISTORY
-- Entirely our own data. No retention restrictions. The product's moat.
-- ===========================================================================

create table profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  home_point   geography(point, 4326),
  created_at   timestamptz not null default now()
);

create table households (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  created_by uuid not null references profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table household_members (
  household_id uuid not null references households(id) on delete cascade,
  user_id      uuid not null references profiles(id) on delete cascade,
  role         text not null default 'member' check (role in ('owner', 'member')),
  joined_at    timestamptz not null default now(),
  primary key (household_id, user_id)
);

-- A visit is the single most valuable row in the system: it powers both the
-- recency decay that breaks the rut and the novelty boost that surfaces new
-- places.
create table visits (
  id           uuid primary key default gen_random_uuid(),
  household_id uuid not null references households(id) on delete cascade,
  place_id     uuid not null references places(id) on delete restrict,
  visited_at   timestamptz not null default now(),
  chosen_by    uuid references profiles(id) on delete set null,
  occasion     text,
  note         text,
  created_at   timestamptz not null default now()
);

create index visits_household_place_idx on visits (household_id, place_id, visited_at desc);
create index visits_recency_idx on visits (household_id, visited_at desc);

create table visit_attendees (
  visit_id uuid not null references visits(id) on delete cascade,
  user_id  uuid not null references profiles(id) on delete cascade,
  primary key (visit_id, user_id)
);

-- Per-user, not per-household: the whole thesis is that YOUR rating steers
-- YOUR app rather than being averaged into anonymity.
create table place_ratings (
  user_id    uuid not null references profiles(id) on delete cascade,
  place_id   uuid not null references places(id) on delete cascade,
  rating     smallint not null check (rating between 1 and 5),
  note       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, place_id)
);

create table place_vetoes (
  user_id    uuid not null references profiles(id) on delete cascade,
  place_id   uuid not null references places(id) on delete cascade,
  reason     text,
  created_at timestamptz not null default now(),
  primary key (user_id, place_id)
);

-- Surfaced-but-skipped. Implicit negative signal, cheap to collect.
create table place_impressions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references profiles(id) on delete cascade,
  place_id     uuid not null references places(id) on delete cascade,
  surfaced_at  timestamptz not null default now(),
  engaged      boolean not null default false
);

create index place_impressions_user_idx on place_impressions (user_id, place_id);

-- --- Group decisioning -----------------------------------------------------

create table meals (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  status            text not null default 'open'
                      check (status in ('open', 'voting', 'decided', 'abandoned')),
  decided_place_id  uuid references places(id) on delete set null,
  created_by        uuid not null references profiles(id) on delete restrict,
  created_at        timestamptz not null default now(),
  decided_at        timestamptz
);

create table meal_candidates (
  meal_id  uuid not null references meals(id) on delete cascade,
  place_id uuid not null references places(id) on delete cascade,
  position smallint not null,
  primary key (meal_id, place_id)
);

create table meal_votes (
  meal_id  uuid not null references meals(id) on delete cascade,
  user_id  uuid not null references profiles(id) on delete cascade,
  place_id uuid not null references places(id) on delete cascade,
  vote     smallint not null check (vote in (-1, 1)),
  voted_at timestamptz not null default now(),
  primary key (meal_id, user_id, place_id)
);

-- ===========================================================================
-- OPS — cost control
-- Google spend is the primary engineering risk (spec §5). Quota enforcement in
-- places-proxy reads from here.
-- ===========================================================================

create table google_api_usage (
  id        bigserial primary key,
  user_id   uuid references profiles(id) on delete set null,
  sku       text not null,
  call_count int not null default 1,
  called_at timestamptz not null default now()
);

create index google_api_usage_user_day_idx
  on google_api_usage (user_id, called_at desc);

-- ===========================================================================
-- RLS — Layer 3 only. The catalog is public read.
-- ===========================================================================

alter table profiles           enable row level security;
alter table households         enable row level security;
alter table household_members  enable row level security;
alter table visits             enable row level security;
alter table visit_attendees    enable row level security;
alter table place_ratings      enable row level security;
alter table place_vetoes       enable row level security;
alter table place_impressions  enable row level security;
alter table meals              enable row level security;
alter table meal_candidates    enable row level security;
alter table meal_votes         enable row level security;

-- Catalog is readable by any authenticated user; writes are service-role only
-- (the ingest pipeline).
alter table places               enable row level security;
alter table cuisines             enable row level security;
alter table place_cuisines       enable row level security;
alter table category_cuisine_map enable row level security;

create policy places_read on places
  for select to authenticated using (true);
create policy cuisines_read on cuisines
  for select to authenticated using (true);
create policy place_cuisines_read on place_cuisines
  for select to authenticated using (true);
create policy category_cuisine_map_read on category_cuisine_map
  for select to authenticated using (true);

create policy profiles_self on profiles
  for all to authenticated using (id = auth.uid()) with check (id = auth.uid());

create policy place_ratings_self on place_ratings
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy place_vetoes_self on place_vetoes
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy place_impressions_self on place_impressions
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Household-scoped access. SECURITY DEFINER avoids recursive RLS evaluation
-- when household_members is itself the table being filtered.
create function is_household_member(h uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from household_members
    where household_id = h and user_id = auth.uid()
  );
$$;

create policy households_member on households
  for select to authenticated using (is_household_member(id));

create policy household_members_member on household_members
  for select to authenticated using (is_household_member(household_id));

create policy visits_member on visits
  for all to authenticated
  using (is_household_member(household_id))
  with check (is_household_member(household_id));

create policy meals_member on meals
  for all to authenticated
  using (is_household_member(household_id))
  with check (is_household_member(household_id));

create policy meal_candidates_member on meal_candidates
  for all to authenticated
  using (exists (select 1 from meals m
                 where m.id = meal_id and is_household_member(m.household_id)))
  with check (exists (select 1 from meals m
                      where m.id = meal_id and is_household_member(m.household_id)));

create policy meal_votes_member on meal_votes
  for all to authenticated
  using (exists (select 1 from meals m
                 where m.id = meal_id and is_household_member(m.household_id)))
  with check (user_id = auth.uid());

create policy visit_attendees_member on visit_attendees
  for all to authenticated
  using (exists (select 1 from visits v
                 where v.id = visit_id and is_household_member(v.household_id)))
  with check (exists (select 1 from visits v
                      where v.id = visit_id and is_household_member(v.household_id)));
